name: Build + Push ooNodz image

on:
  push:
    branches:
      - aylin

defaults:
  run:
    shell: bash

jobs:
  build_oonodz_image:
    name: Build Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASS }} 
      - name: Build Dockerfile for Fuji
        run: |
          CURRENT_BRANCH=${{ github.head_ref || github.ref_name }} 
          PUSH_DOCKER_IMAGE=true 
          GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          BUILD_IMAGE_ID=${AVALANCHE_VERSION}-fuji-${GITHUB_SHA_SHORT}
          echo "COPY --from=builder /build/jvrKsTB9MfYGnAXtxbzFYpXKceXr9J8J8ej6uWGrYM5tXswhJ /root/.avalanchego/plugins/jvrKsTB9MfYGnAXtxbzFYpXKceXr9J8J8ej6uWGrYM5tXswhJ" >> Dockerfile
          ./scripts/build_image.sh
